.github/workflows/coverage.yml
https://github.com/golang/go/issues/13560#issuecomment-288457920
---
---
=> Exclude mocks from code coverage

commonspace/headsync/diffsyncer_test.go, consensus/consensusclient/client.go, net/peer/mock_peer/mock_peer.go, net/peer/peer.go, net/peer/peer_test.go, net/pool/pool_test.go
=> GO-1859 consensus connection

commonspace/objectmanager/objectmanager.go
=> Go-1865: Fix id crash

.github/workflows/coverage.yml
=> .github/workflows/ updated go-version to 1.21.0

coordinator/coordinatorclient/coordinatorclient.go
=> GO-1982: Add force request to coordinator client

coordinator/coordinatorclient/coordinatorclient.go
=> GO-1986: Fix marshal payload

.github/workflows/coverage.yml
=> .github/workflows/coverage.yml updated golang version and refactoring

commonspace/headsync/headsync.go
=> GO-2289: Fix acl id filtering

commonspace/spaceservice.go, go.mod, go.sum, net/peerservice/peerservice.go, net/peerservice/peerservice_test.go
=> GO-2340 p2p space pull

net/streampool/streampool.go, net/streampool/streamstat.go
=> GO-2499: Atomic counting of streampool params

commonspace/requestmanager/requestmanager.go, commonspace/requestmanager/requestpool.go, commonspace/requestmanager/requestpool_test.go
=> GO-2482: Add request pool with replace requests

commonspace/requestmanager/requestmanager.go, commonspace/requestmanager/requestpool.go, commonspace/requestmanager/requestpool_test.go
=> GO-2511: Fix queue add

app/ldiff/diffcontainer.go, app/ldiff/diffcontainer_test.go, app/ldiff/olddiff.go
=> GO-2526: Change diff container locking

net/peerservice/peerservice.go, net/peerservice/peerservice_test.go, net/transport/mock_transport/mock_transport.go, net/transport/quic/conn.go, net/transport/transport.go, net/transport/yamux/conn.go
=> GO-2615 conn close chan

commonspace/headsync/diffsyncer_test.go, net/peer/mock_peer/mock_peer.go, net/peer/peer.go, net/pool/pool_test.go
=> CloseChan peer interface

app/ocache/ocache.go, app/ocache/ocache_test.go
=> GO-1293 Remove ocache goroutine

commonspace/object/acl/list/acltestsuite.go, commonspace/object/acl/list/acltestsuite_test.go, commonspace/object/tree/objecttree/objecttree.go, commonspace/object/tree/objecttree/objecttree_test.go, commonspace/object/tree/objecttree/objecttreefactory.go, commonspace/object/tree/objecttree/objecttreevalidator.go, commonspace/object/tree/objecttree/tree.go
=> GO-2790: Validate keys and add tests

net/secureservice/secureservice.go
=> GO-2925 define proto version 3

commonspace/acl/aclclient/acjoiningclient.go, commonspace/acl/aclclient/aclspaceclient.go, commonspace/spaceutils_test.go
=> GO-2937: Change to coordinator client

commonspace/acl/aclclient/aclspaceclient.go, commonspace/object/acl/list/aclrecordbuilder.go, commonspace/object/acl/list/aclstate.go, commonspace/object/acl/list/aclstatebuilder.go, commonspace/object/acl/list/acltestsuite.go, commonspace/object/acl/list/acltestsuite_test.go, commonspace/object/acl/list/list.go, commonspace/object/acl/list/list_test.go, commonspace/object/acl/list/mock_list/mock_list.go, commonspace/object/acl/list/validator.go, commonspace/object/acl/syncacl/mock_syncacl/mock_syncacl.go, commonspace/object/tree/objecttree/objecttree_test.go
=> Go 2966 multiple changes one record

commonspace/acl/aclclient/aclspaceclient.go, commonspace/object/acl/list/acltestsuite_test.go
=> GO-2971: Revoke invites

commonspace/acl/aclclient/acjoiningclient.go
=> GO-2972: Add cancel remove self

commonspace/acl/aclwaiter/aclwaiter.go
=> GO-2982: Provide acl in aclwaiter

app/debugstat/stat.go
=> GO-3009: Add composite id for stat providers

acl/acl.go
=> GO-3062 fix limit checking

coordinator/coordinatorclient/coordinatorclient.go
=> GO-3072 consensus client: rpcerr unwrap

net/rpc/rpcerr/registry.go
---
---
This PR fixes error formatting in case error with Code is not registered
https://linear.app/anytype/issue/GO-3168/fix-error-formatting-in-rpc-error-unwrapper
=> GO-3168 Fix RPC error formatting

commonspace/spaceservice.go
=> GO-3213 close spacestore on create/derive

net/secureservice/secureservice.go
=> GO-2934 proto version 3

net/peer/peer.go
=> GO-3370 extra conn close

net/transport/quic/quic.go
=> GO-3370 close quic connection on failed handshake

acl/acl.go
=> GO-3385 acl members limits: counts writers

commonspace/objectsync/objectsync.go
=> GO-3411 panic recover

.github/workflows/coverage.yml
=> .github/workflows/coverage.yml moved on reusable workflow

go.mod, go.sum
=> Bump go-ethereum

commonspace/object/tree/objecttree/objecttree.go, commonspace/object/tree/objecttree/objecttree_test.go, commonspace/object/tree/objecttree/objecttreevalidator.go
=> GO-3482: Add verbose errors

commonspace/object/tree/objecttree/mock_objecttree/mock_objecttree.go, commonspace/object/tree/objecttree/objecttree.go, commonspace/object/tree/objecttree/objecttree_test.go, commonspace/object/tree/objecttree/objecttreevalidator.go, commonspace/object/tree/synctree/mock_synctree/mock_synctree.go, util/debug/stack.go, util/debug/stack_test.go
=> GO-3495: Fix invalid change and add logs

net/transport/yamux/yamux.go
=> Decrease log level for some connection errors

nameservice/nameserviceclient/nameserviceclient.go, paymentservice/paymentserviceclient/paymentserviceclient.go
=> pp/ns clients: add nodeconf ID to error

commonspace/object/tree/synctree/mock_synctree/mock_synctree.go, commonspace/object/tree/synctree/synctree.go, commonspace/object/tree/synctree/synctree_test.go, commonspace/object/tree/synctree/synctreehandler.go, commonspace/object/tree/synctree/synctreehandler_test.go, commonspace/object/tree/synctree/treeremotegetter.go, commonspace/object/tree/synctree/treeremotegetter_test.go, commonspace/object/tree/synctree/treesyncprotocol.go, commonspace/object/tree/synctree/treesyncprotocol_test.go, commonspace/object/tree/synctree/utils_test.go, commonspace/syncstatus/noop.go, commonspace/syncstatus/syncstatus.go
=> GO-3769: Sync status updates

coordinator/coordinatorclient/mock_coordinatorclient/mock_coordinatorclient.go
=> Add missing mocks for coordinatorclient

nodeconf/nodeconfstore/nodeconfstore.go
=> fix: file perm

commonspace/object/tree/synctree/mock_synctree/mock_synctree.go, commonspace/object/tree/synctree/synctree.go, commonspace/object/tree/synctree/synctreehandler.go, commonspace/object/tree/synctree/synctreehandler_test.go, commonspace/object/tree/synctree/treesyncprotocol.go, commonspace/object/tree/synctree/treesyncprotocol_test.go, net/streampool/streampool.go
Handle empty head updates from new sync protocol
=> GO-3690: Intermediate sync protocol fix

nodeconf/service.go, nodeconf/service_test.go
=> GO-3971: Fix nodeconf empty configuration

nameservice/nameserviceclient/nameserviceclient.go, paymentservice/paymentserviceclient/paymentserviceclient.go
=> Add err messages to ns/pp clients

commonspace/object/tree/objecttree/change.go, commonspace/object/tree/objecttree/flusher.go, commonspace/object/tree/objecttree/mock_objecttree/mock_objecttree.go, commonspace/object/tree/objecttree/objecttree.go, commonspace/object/tree/objecttree/objecttree_test.go, commonspace/object/tree/objecttree/objecttreefactory.go, commonspace/object/tree/objecttree/objecttreevalidator.go, commonspace/object/tree/objecttree/tree.go, commonspace/object/tree/objecttree/tree_test.go, commonspace/object/tree/objecttree/treegraph_nix.go, commonspace/object/tree/synctree/mock_synctree/mock_synctree.go, commonspace/object/tree/synctree/synctree.go, commonspace/object/tree/synctree/synctree_test.go, commonspace/object/tree/synctree/updatelistener/mock_updatelistener/mock_updatelistener.go, commonspace/object/tree/synctree/updatelistener/updatelistener.go, commonspace/settings/settingsobject.go, coordinator/coordinatorclient/mock_coordinatorclient/mock_coordinatorclient.go
=> GO-3996: Add tree transactions

commonspace/object/tree/objecttree/change.go, commonspace/object/tree/objecttree/flusher.go, commonspace/object/tree/objecttree/mock_objecttree/mock_objecttree.go, commonspace/object/tree/objecttree/objecttree.go, commonspace/object/tree/objecttree/objecttree_test.go, commonspace/object/tree/objecttree/objecttreefactory.go, commonspace/object/tree/synctree/mock_synctree/mock_synctree.go, commonspace/object/tree/synctree/synctree.go, commonspace/object/tree/synctree/synctree_test.go
=> GO-3652: New tree logic chats

commonspace/sync/objectsync/synchandler.go, commonspace/sync/requestmanager.go
=> GO-4304: Fix error handling

.github/dependabot.yml
=> Change dependabot limit

commonspace/object/tree/objecttree/objecttree.go, commonspace/object/tree/objecttree/objecttree_test.go
=> GO-4375: Fix deletion check

commonspace/space.go
=> GO-4375: Add creation time

net/peerservice/peerservice.go
otherwise SetPeerAddrs call will hang in case of long dials
=> peerservice: do not dial under rlock

util/slice/slice.go, util/slice/slice_test.go
=> GO-4409: Fix contains sorted

net/secureservice/credential.go, net/secureservice/credential_test.go
=> GO-4423 hotfix: blacklist middle 36.6

nameservice/nameserviceclient/nameserviceclient.go, paymentservice/paymentserviceclient/paymentserviceclient.go
=> pp/ns: extra log msgs and comments

commonspace/object/tree/objecttree/change.go, commonspace/object/tree/objecttree/loaditerator.go, commonspace/object/tree/objecttree/objecttree.go, commonspace/object/tree/objecttree/objecttree_test.go, commonspace/object/tree/objecttree/objecttreefactory.go, commonspace/object/tree/objecttree/objecttreevalidator.go, commonspace/object/tree/objecttree/tree.go, commonspace/object/tree/objecttree/tree_test.go, commonspace/object/tree/objecttree/treereduce.go, commonspace/object/tree/synctree/responsecollector.go, commonspace/object/tree/synctree/responsecollector_test.go, commonspace/object/tree/synctree/treeremotegetter.go, commonspace/object/tree/synctree/treeremotegetter_test.go
=> GO-4433: Optimize tree reduce/validation

commonspace/object/tree/synctree/responsecollector.go, commonspace/object/tree/synctree/responsecollector_test.go
=> GO-4453: Fix locking log messages

commonspace/object/tree/objecttree/objecttree.go, commonspace/object/tree/objecttree/objecttree_test.go, commonspace/object/tree/objecttree/objecttreevalidator.go
=> GO-4458: Correct rollback

commonspace/headsync/diffsyncer.go
=> GO-3957 Clean up logs

commonspace/deletionmanager/mock_deletionmanager/mock_deletionmanager.go, commonspace/headsync/diffsyncer.go, commonspace/headsync/diffsyncer_test.go, commonspace/peermanager/mock_peermanager/mock_peermanager.go, commonspace/peermanager/peermanager.go, commonspace/spaceutils_test.go, commonspace/sync/sync_test.go, commonspace/sync/synctest/testpeermanager.go, util/periodicsync/periodicsync_test.go
=> GO-4285 stream keep alive

paymentservice/paymentserviceclient/paymentserviceclient.go
=> payments: remove unnecessary log msg

commonspace/deletion_test.go, commonspace/object/acl/list/aclstate.go, commonspace/object/acl/list/list_test.go, commonspace/object/tree/objecttree/objecttree.go, commonspace/object/tree/objecttree/objecttree_test.go
=> GO-4607: Fix incorrect root validation

commonspace/deletion_test.go, commonspace/object/acl/syncacl/syncacl.go, commonspace/object/tree/synctree/synctree.go, net/secureservice/secureservice.go
=> GO-4663: Upgrade protocol

app/app.go, app/apptrace.go
=> GO-3508 Add dependencies tracing

commonspace/headsync/headsync.go, commonspace/headsync/headsync_test.go, commonspace/object/tree/objecttree/changebuilder.go, commonspace/object/tree/objecttree/derivedtree.go, commonspace/object/tree/synctree/synctree.go, commonspace/object/tree/synctree/synctree_test.go
=> GO-4740: Derived tree fixes

net/secureservice/config.go, net/secureservice/secureservice.go
=> GO-3682 secure service: config for identity check

app/ocache/ocache.go, app/ocache/ocache_test.go
=> GO-2076 Add TryRemove method to Ocache

commonspace/object/acl/syncacl/syncacl.go, commonspace/object/tree/objecttree/storage.go, commonspace/object/tree/objecttree/testutils.go, commonspace/object/tree/synctree/synchandler.go, commonspace/object/tree/synctree/synchandler_test.go, commonspace/payloads.go, commonspace/spaceservice.go, commonspace/spaceutils_test.go, commonspace/sync/objectsync/objectsync_test.go, commonspace/sync/objectsync/synchandler.go, commonspace/sync/requestmanager.go, commonspace/sync/sync.go, go.mod
=> GO-5208: Expose stuff for testing

commonspace/headsync/statestorage/statestorage.go, commonspace/object/acl/list/storage.go, commonspace/object/tree/objecttree/storage.go, commonspace/spacestorage/spacestorage.go, commonspace/spacestorage_test.go
=> GO-5228: Create space storage in one transaction

go.mod, go.sum
=> GO-5262: Update any-store

commonspace/object/tree/objecttree/storage.go
=> GO-5311: Fix parser issue in tree, add comments

commonspace/headsync/diffsyncer.go, paymentservice/paymentserviceclient/paymentserviceclient.go
=> GO-5309 Cleanup graylog

net/peer/peer.go
=> GO-5377 peer: fix closed connection release

commonspace/headsync/statestorage/statestorage.go
=> GO-5520: Add legacy hash key to state storage

commonspace/headsync/statestorage/statestorage.go
=> GO-5520: Fix misplaced hashes

commonspace/spacestorage/migration/spacemigrator.go
=> GO-5570: Simplify space migrator and fix not removing on error

net/secureservice/secureservice.go
=> GO-5667: Update proto versions

commonspace/object/acl/list/aclrecordbuilder.go, commonspace/object/acl/list/acltestsuite_test.go, commonspace/object/acl/list/validator.go
=> GO-5679: Request to join checks

app/ldiff/diff.go
=> GO-5741 optimize ldiff compare

commonspace/object/tree/objecttree/changediffer.go
=> GO-5898: Add get ids

commonspace/sync/objectsync/objectmessages/headupdate.go
=> GO-6069: Fix headupdate reuse

net/secureservice/secureservice.go
=> GO-6232 update proto version

commonspace/deletion_test.go
=> GO-6330 fix flickering test
